{{- if .Values.ingress.tls }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tls-sc
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.tls.crt }}
  tls.key: {{ .Values.ingress.tls.key }}
...
{{- end }}
